server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: crm-user-service
  datasource:
    url: ${DB_URL:jdbc:h2:file:./crm-user;AUTO_SERVER=TRUE}
    username: ${DB_USERNAME:crm}
    password: ${DB_PASSWORD:crm}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: ${LIQUIBASE_CONTEXTS:local}
  h2:
    console:
      enabled: false
